try
Signed-off-by: Sa Sajjad <sqsa93103@gmail.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -122,7 +122,7 @@ jobs:
                       ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
               fi
               git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests && \
-              timeout 1m repo sync --force-sync || { exit_code=$?; [ $exit_code -eq 124 ] || (echo "Error: Process failed with exit code $exit_code"; exit $exit_code); }
+              timeout 30s repo sync --force-sync || { exit_code=$?; [ $exit_code -eq 124 ] || (echo "Error: Process failed with exit code $exit_code"; exit $exit_code); }
               rm -rf .repo
       timeout-minutes: 5
       
@@ -141,6 +141,29 @@ jobs:
       env:
         CRAVE_USERNAME: ${{  secrets.CRAVE_USERNAME  }}
         CRAVE_TOKEN: ${{  secrets.CRAVE_TOKEN  }}
+
+    # Initialize the previously choosen 'repo' project.
+    - name: Set the 'crave' project
+      run: |
+        case "${{ github.event.inputs.BASE_PROJECT }}" in
+          "ArrowOS 13.1")
+            repo init -u https://github.com/ArrowOS/android_manifest.git -b arrow-13.1 --depth=1
+            crave set --projectID 73
+          ;;
+          "DerpFest 13.0")
+            repo init -u https://github.com/DerpFest-AOSP/manifest.git -b 13 --depth=1
+            crave set --projectID 64
+          ;;
+          "LineageOS 21.0")
+            repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --git-lfs --depth=1
+            crave set --projectID 72
+          ;;
+          "LineageOS 20.0")
+            repo init -u https://github.com/accupara/los20.git -b lineage-20.0 --git-lfs --depth=1
+            crave set --projectID 36
+          ;;
+        esac
+      id: pwd
 
       # Create a 'crave' job for building.
     - name: Start compilation through 'crave'
